### ISSUE TITLE
Configure ICMP extraction send rate

### ISSUE THREAD

**Issue by GinjaChris** [GinjaChris/pentmenu#39]
Currently the ICMP file extraction module is hard coded to send 100 bytes of data with every ICMP packet (which is 100 bytes per second in effect).
I should make this configurable.
Presumaby anything between 1 and say, 1200 bytes would be reasonable, with the default being a sensible value.  It's possible that large ICMP packets would be dropped by a firewall so 100 bytes seems a sesible default, unless there are any sensible suggestions to the contrary?

**Comment by GinjaChris** [comment]
ICMP extraction module removed from script due to its instability - it's fine for transferring a little text but for anything else it's of no use. 
So, currently closing this issue as "invalid".

**Comment by Luckydamian1** [comment]
[]()]()
