### ISSUE TITLE
readme.md translation - help wanted

### ISSUE THREAD

**Issue by GinjaChris** [GinjaChris/pentmenu#50]
I'd like to request assistance accurately translating readme.md to other languages e.g. Spanish, Russian, anything!

**Comment by ch4rc0al1080** [comment]
I can help you translate it to Chinese

**Comment by GinjaChris** [comment]
@kinglyl yes please that would be great!

**Comment by ch4rc0al1080** [comment]
> @kinglyl yes please that would be great!

https://github.com/GinjaChris/pentmenu/pull/54

**Comment by GinjaChris** [comment]
@kinglyl sorry it took so long, changes are now merged.  Thank you very much for your help!

**Comment by GinjaChris** [comment]
Closing.   Kinglyl was kind enough to help with translation to Chinese and there has been no interest in other languages.
