### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by STRESSEDD** [GinjaChris/pentmenu#51]
Im on MacOS and i launched the latest version (downloaded in a zip folder). The menu is working perfectly fine. When i select dos, and i want to select slowloris with 9, i cant type in the target, because it says this:
Enter target:
/Users/Aron/Downloads/pentmenu-master/pentmenu: line 939: read: -i: invalid option
read: usage: read [-ers] [-u fd] [-t timeout] [-p prompt] [-a array] [-n nchars] [-d delim] [name ...]
Target is set to 
Enter target port (defaults to 80):
/Users/Aron/Downloads/pentmenu-master/pentmenu: line 943: read: -i: invalid option
read: usage: read [-ers] [-u fd] [-t timeout] [-p prompt] [-a array] [-n nchars] [-d delim] [name ...]
Using Port 80
Enter number of connections to open (default 2000)

I dont know what is happening, please help me, i want to use it.

**Comment by GinjaChris** [comment]
It looks like MacOS doesn't support the "-i" option with the read command.
Line 939 of the code for example is:
read -i $TARGET -e TARGET

I've never tested on a Mac to be fair.
You could try modifying the code, or install a Virtual Machine running Linux?

**Comment by STRESSEDD** [comment]
> It looks like MacOS doesn't support the "-i" option with the read command.
> Line 939 of the code for example is:
> read -i $TARGET -e TARGET
> 
> I've never tested on a Mac to be fair.
> You could try modifying the code, or install a Virtual Machine running Linux?

How could i modify it?

**Comment by GinjaChris** [comment]
Well, I don't have a Mac to test with and I'm not going to pretend to know anything about Macs, but you could try:
chsh /bin/bash
and then try the script again.
I think you may use zsh by default?

**Comment by GinjaChris** [comment]
Going to assume this is resolved due to no further comments.
Problem: script misbehaves when not run in bash shell.
Solution: run bash script in bash shell
