### ISSUE TITLE
pentmenu Dos problem

### ISSUE THREAD

**Issue by GTRacing65** [GinjaChris/pentmenu#52]
Hello i have a Problem i only want to attack a Computer with the DOS Attack but if i start the DOS Attack on the Target IP (Computer) (all DOS Methods) it hits my Router as well but i only used the Target IP from the Computer and not from the Router and my Phone IP for the Source IP sry for my bad english

**Comment by ayvdaualo** [comment]
Well really you need to think about what you are actually doing. Since your phone and your computer are possibly wirelessly connected through your router, and you start a dos, of course the traffic will go through your router

**Comment by GTRacing65** [comment]
? but then why i can dos with EvilFOCA which only hits the Target IP and doesnt hits the Router as well like 
pentmenu? (hping3)

**Comment by GinjaChris** [comment]
This doesn't sound like a problem with the script.
If you are using "normal" infrastructure mode wireless, packets will have to traverse the wireless access point (usually your router).
If you think something else is going on here please provide an example.

**Comment by GinjaChris** [comment]
No response so closing this as not a script problem but rather a network misunderstanding.
