### ISSUE TITLE
ICMP extraction module removed from script due to its instability - it's fine for transferring a little text but for anything else it's of no use.

### ISSUE THREAD

**Issue by Luckydamian1** [GinjaChris/pentmenu#61]
ICMP extraction module removed from script due to its instability - it's fine for transferring a little text but for anything else it's of no use. 
So, currently closing this issue as "invalid".

_Originally posted by @GinjaChris in https://github.com/GinjaChris/pentmenu/issues/39#issuecomment-274482238_

**Comment by GinjaChris** [comment]
I have no idea what your issue is, please explain.
